### ISSUE TITLE
What is development target for this repertory?

### ISSUE THREAD

**Issue by Linjieqiang** [betaflight/betaflight-configurator-ng#1]

**Comment by mikeller** [comment]
This is for the next generation version of the Betaflight configurator, that will become a replacement for the chrome web store version based configurator. Unfortunately we don't have a target version / date yet, so if you need changes to work with firmware 3.1, you should raise PRs against https://github.com/betaflight/betaflight-configurator for now.

**Comment by Linjieqiang** [comment]
Oh,I see.

**Comment by Linjieqiang** [comment]
How about using phonegap frame to develop?It will support many platform such as android,ios,win,linux. https://build.phonegap.com/
